server:
  port: 8080
  servlet:
    context-path: /u
spring:
  application:
    name: user-service

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/chat-bot-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

key:
  public: keys/public.pem
