server:
  port: 8080
  servlet:
    context-path: /u
spring:
  application:
    name: user-service

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/chat-bot-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 2MB

key:
  public: keys/public.pem

minio:
  endpoint: http://127.0.0.1:9001
  user: user
  password: password
  bucketName: user-service

