version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: chat-bot-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chat-bot-db
    ports:
      - "5433:5432"

  minio:
    image: minio/minio
    container_name: minio-chat-bot
    ports:
      - "9001:9000"
      - "9002:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    command:
      - server
      - /data
      - --console-address
      - :9001
