version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: chat-bot-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chat-bot-db
    ports:
      - "5433:5432"